<?php

/**
 * @file
 * Contains iq_user_base.module.
 */

use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function iq_user_base_theme($existing, $type, $theme, $path) {
  return [
    'block__userareamenu' => [
      'template' => 'block/block--userareamenu',
      'base hook' => 'block',
    ],
    'page__user__%' => [
      'template' => 'layout/page--user--%',
      'base hook' => 'page',
    ],
    'page__user__edit' => [
      'template' => 'layout/page--user--edit',
      'base hook' => 'page',
    ],
    'page__user__login' => [
      'template' => 'layout/page--user--login',
      'base hook' => 'page',
    ],
    'page__user__password' => [
      'template' => 'layout/page--user--password',
      'base hook' => 'page',
    ],
    'page__user__register' => [
      'template' => 'layout/page--user--register',
      'base hook' => 'page',
    ],
    'menu__user_area_menu' => [
      'template' => 'navigation/menu--user-area-menu',
      'base hook' => 'menu',
    ],
    'user__full' => [
      'template' => 'user/user--full',
      'base hook' => 'user',
    ],
    'swiftmailer__user' => [
      'template' => 'swiftmailer/swiftmailer--user',
      'base hook' => 'swiftmailer',
    ],
  ];
}

/**
 * Implements hook_preprocess_block__userareamenu().
 */
function iq_user_base_preprocess_block__userareamenu(&$variables) {
  // Get username.
  if (!in_array('anonymous', $variables['user']->getRoles())) {
    $variables['name'] = $variables['user']->getDisplayName();
  }
  $variables['destination'] = Url::fromRoute('<current>')->toString();

  // Get current language.
  $language = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();
  $variables['language'] = $language;
}

/**
 * Implements hook_preprocess_menu__user_area_menu().
 */
function iq_user_base_preprocess_menu__user_area_menu(&$variables) {
  foreach ($variables['items'] as &$item) {
    $current = Url::fromRoute('<current>');
    $url = $item['url'];
    if (preg_replace('/(\/[\d]+)/', '', $current->toString()) == $url->toString()) {
      $item['in_active_trail'] = TRUE;
    }
    else {
      $item['in_active_trail'] = FALSE;
    }
  }
}

/**
 * Implements hook_preprocess_swiftmailer().
 */
function iq_user_base_preprocess_swiftmailer(&$variables) {
  $logoPath = \Drupal::theme()->getActiveTheme()->getLogo();
  if ($wrapper = \Drupal::service('stream_wrapper_manager')->getViaUri($logoPath)) {
    $variables['path_to_logo'] = $wrapper->getExternalUrl();
  }
}
