<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function iq_user_base_theme($existing, $type, $theme, $path) {
  return [
    'block__menu_block__account' => [
      'template' => 'block/block--menu-block--account',
      'base hook' => 'block',
    ],
    'page__user__%' => [
      'template' => 'layout/page--user--%',
      'base hook' => 'page',
    ],
    'page__user__edit' => [
      'template' => 'layout/page--user--edit',
      'base hook' => 'page',
    ],
    'page__user__login' => [
      'template' => 'layout/page--user--login',
      'base hook' => 'page',
    ],
    'page__user__password' => [
      'template' => 'layout/page--user--password',
      'base hook' => 'page',
    ],
    'page__user__register' => [
      'template' => 'layout/page--user--register',
      'base hook' => 'page',
    ],
    'menu__user_area_menu' => [
      'template' => 'navigation/menu--user-area-menu',
      'base hook' => 'menu',
    ],
    'user__full' => [
      'template' => 'user/user--full',
      'base hook' => 'user',
    ],
  ];
}

/**
 * Implements hook_preprocess_user().
 */
function iq_user_base_preprocess_user(&$variables) {
  /** @var User $account */
  $account = $variables['elements']['#user'];

  $variables['name'] = $account->getDisplayName();
  $variables['email'] = $account->getEmail();

  $created = $account->getCreatedTime();
  $variables['created'] = \Drupal::service('date.formatter')->format($created, 'custom', 'd.m.Y');
}
